namespace Game.States
{
    public enum StateTriggers
    {
        None,
        SplashLoading,
        SplashCompleted,
        IntroScene,
        ReturnMainMenuFromAchievements,
        OpenAchievement,
        OpenCard,
        OpenSpaceship,
        ReturnToInventory,
        GoToMarketRequest,
        GoToMainMenuRequest,
        GoToAchievementsRequest,
        GoToSpaceShipUpgradeRequest,
        GoToGarageRequest,
        GoToSettingsRequest,
        GoToInventoryRequest,
        GoToCoPilotRequest,
        GoToQuoteRequest,
        StartGameRequest,
        PlayGameRequest,
        PauseGameRequest,
        ResumeGameRequest,
        GameOver,
        ReplayGameRequest,
        GoToCredits,
        ReturnMainMenuFromGame
    }
}